version: '3'

services:
  backend:
    build: ./backend
    links:
      - db
    ports:
      - '5000:5000'

  db:
    image: mysql:8.0
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: master_20
      MYSQL_USER: herramienta
      MYSQL_PASSWORD: master_20
      MYSQL_DATABASE: herramienta_anotacion
    volumes:
      - mysql_db:/var/lib/mysql
  administracion:
    build: ./administracion
    ports:
      - '4200:80'

  visualizacion:
    build: ./visualizacion
    ports:
      - '4201:80'

volumes:
  mysql_db: